on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
      - name: generate fixture
        run: DOCKER_BUILDKIT=1 docker build -f test/Dockerfile -o . .
      - run: go test
